In [30]:
#numpyのインポート
import numpy as np#npとしてnumpyをインポート

x=np.array([1,2,3])#arrayコンストラクターでベクトルを生成
print(x)
print(x[0])
x[2]=100
print(x)

[1 2 3]
1
[  1   2 100]


In [7]:
#ベクトルの算術演算
import numpy as np#npとしてnumpyをインポート

x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
#ベクトルのスカラー演算
import numpy as np#npとしてnumpyをインポート

x=np.array([1,2,3,4,5],dtype=np.float)
print(x)
#numpyのndarrayオブジェクトとして作成したベクトル列はループなしで一括処理可能
print(x+10)
print(x-1)
print(x*10)
print(x/2)
print(x//2)#割り算結果を整数だけにする
print(x%2)#剰余

[1. 2. 3. 4. 5.]
[11. 12. 13. 14. 15.]
[0. 1. 2. 3. 4.]
[10. 20. 30. 40. 50.]
[0.5 1.  1.5 2.  2.5]
[0. 1. 1. 2. 2.]
[1. 0. 1. 0. 1.]


In [21]:
#ベクトルの累乗、平方根
import numpy as np#npとしてnumpyをインポート

x=np.array([1,2,3,4,5],dtype=float)
print(np.power(x,2))#累乗
print(x**2)#累乗
print(np.sqrt(x))#平方根

[ 1.  4.  9. 16. 25.]
[ 1.  4.  9. 16. 25.]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [26]:
#平均、分散、最大値、最小値
import numpy as np#npとしてnumpyをインポート

x=np.array([35,40,45,50,55,60],dtype=float)
print(np.max(x))
print(np.min(x))
print(np.mean(x))#平均
print(np.var(x))#分散
print(np.std(x))#標準偏差

60.0
35.0
47.5
72.91666666666667
8.539125638299666


In [29]:
#ベクトル同士の四則演算
import numpy as np#npとしてnumpyをインポート

vec1=np.array([10,20,30])
vec2=np.array([40,50,60])

print(vec1+vec2)
print(vec1-vec2)
print(vec1/vec2)#ベクトル同士の割り算は本来はできないので注意

[50 70 90]
[-30 -30 -30]
[0.25 0.4  0.5 ]


In [31]:
#ベクトル要素同士の積（アダマール積）
import numpy as np#npとしてnumpyをインポート

vec1=np.array([10,20,30])
vec2=np.array([40,50.,60])

print(vec1*vec2)#ベクトル同士のアダマール積

array([ 400., 1000., 1800.])

In [4]:
#ベクトルの内積
import numpy as np#npとしてnumpyをインポート

vec1=np.array([2,3])
vec2=np.array([4,5])
print(np.dot(vec1,vec2))#ベクトルの内積
vec3=np.array([4,5,-6])
vec4=np.array([-2,3,-1])
print(np.dot(vec3,vec4))#ベクトルの内積

23
13


In [3]:
#多次元配列で行列を表現する
import numpy as np#npとしてnumpyをインポート

mtx=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]],
            dtype=float)
print(mtx)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
#行列のスカラー演算
import numpy as np#npとしてnumpyをインポート

mtx=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],
              dtype=np.float)
print(mtx+10)
print(mtx-10)
print(mtx*2)
print(mtx/2)
print(mtx%2)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]
[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [21]:
#行列の成分にアクセスする
import numpy as np#npとしてnumpyをインポート

mtx=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]]
            )

print(mtx.dtype)#データ型を確認

print(mtx[0])
print(mtx[0,])
print(mtx[0,:])
print(mtx[:,0])
print(mtx[1,1])
print(mtx[0:2,0:2])

int64
[1 2 3]
[1 2 3]
[1 2 3]
[1 4 7]
5
[[1 2]
 [4 5]]


In [25]:
#行列の要素同士の加算減算
import numpy as np

a=np.array([[1,2],
            [3,4]]
          )

b=np.array([[4,3],
            [2,1]]
          )

print(a+b)
print(a-b)

[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]


In [27]:
#行列の積
import numpy as np

a=np.array([[1,2],
            [3,4]]
          )
b=np.array([[5,6],
            [7,8]]
          )

print(a*b)#アダマール積
print(np.dot(a,b))#行列の積

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [31]:
#転置行列
import numpy as np

a=np.array([[1,2,3],
            [4,5,6]]
          )

print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]
